project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: HandsOnEx\HandsOnEx01\HandsOnEx01.qmd
          - text: Hands-on Exercise 2
            href: HandsOnEx\HandsOnEx02\HandsOnEx02.qmd
      - text: In-Class Exercises
        menu: 
          - text: In-class Exercise 1
            href: InClassEx\InClassEx01\InClassEx01.qmd
          - text: In-class Exercise 2        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

