project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: HandsOnEx\HandsOnEx01\HandsOnEx01.qmd
          - text: Hands-on Exercise 2
            href: HandsOnEx\HandsOnEx02\HandsOnEx02.qmd
          - text: Hands-on Exercise 3
            href: HandsOnEx\HandsOnEx03\HandsOnEx03.qmd            
      - text: In-Class Exercises
        menu: 
          - text: In-class Exercise 1
            href: InClassEx\InClassEx01\InClassEx01.qmd
          - text: In-class Exercise 2      
      - text: Take Home Exercises
        menu: 
          - text: Take Home Exercise 1
            href: TakeHomeEx\TakeHomeEx01\TakeHomeEx01.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

